#spring:
#  jpa:
#    database: mysql
#    show-sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        type: trace
#192.168.0.115

multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://localhost:3306/master_db?useSSL=false
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool

    tenant:
      datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        url : jdbc:mysql://localhost:3306/
        

server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      indent-output: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
mymodule:
  bespa:
    modules:
      - admin
      #- login
      #- billing
    test:
      abc
